### ISSUE TITLE
First control from different device than what's used until that point fails to propagate

### ISSUE THREAD

**Issue by TMaYaD** [Cossid/TasmotaDeviceGroupsForESPHome#8] opened 2023-12-23 00:15 UTC
I use device groups to sync my wall touch switches with light channels. The device groups work wonderfully most of the time. The only problem is when I try to switch OFF using a different device to the one I used to switch ON.

Ex: 
- Turn ON using wall switch, Light turns ON
  Turn OFF using wall switch, Lights turns OFF ✅ 
- Turn ON using Light, Switch turns ON
  Turn OFF using Light, Switch turns OFF ✅ 

- Turn ON using wall switch, Light goes ON
  Turn OFF using Light, Switch stays ON ❌
  Turn OFF light, Turn it back ON and then turn it OFF one more time, Switch turns OFF
- Turn ON using Light, Switch turns ON
  Turn OFF using switch, Light stays ON ❌
  Turn OFF switch, Turn it back ON and then turn it OFF one more time, Light turns OFF

**Comment by TMaYaD** [comment] 2023-12-23 00:27
Changed the title because as I was experimenting, I saw the same happen when trying to turn light "ON" as well.

**Comment by TMaYaD** [comment] 2023-12-23 00:30
Here's a sample log from the light:

```
05:55:42	[D]	[light:036]	
'theater Room Lights' Setting:
05:55:42	[D]	[light:047]	
  State: ON
05:55:42	[D]	[light:085]	
  Transition length: 1.0s
05:55:42	[D]	[dgr:736]	
Sending theater-lights message to network: seq=79, flags=0, 128=335544321
05:55:42	[D]	[dgr:736]	
Sending theater-lights message to network: seq=80, flags=0, 128=335544321, 224=209,0,255,255,255,0
05:55:42	[D]	[dgr:736]	
Received theater-lights message from 10.10.10.211: seq=79, flags=8
05:55:42	[D]	[dgr:736]	
Received theater-lights message from 10.10.10.211: seq=80, flags=8
05:55:47	[D]	[dgr:736]	
Sending theater-lights message to 10.10.10.211: seq=43, flags=8
05:55:47	[D]	[dgr:736]	
Received theater-lights message from 10.10.10.211: seq=43, flags=0, 128=335544320*
```

I was using the light's web interface @ 05:55:42 and the touch switch at @ 05:55:47. The message is received fine. But for some reason the light chooses to ignore it.

**Comment by Cossid** [comment] 2023-12-23 01:01
While I'm sure this happens, and have likely experienced myself in production when I'm not able to debug, I can't currently reproduce it intentionally.  I can Turn on with a switch, off with a light, and back on with the original switch on the first try.  I can also do the inversion of that (light->switch->light).

Do you have any custom masks set?

**Comment by TMaYaD** [comment] 2023-12-23 01:20
Yes.

```yaml
  - group_name: "theater-lights"
    receive_mask: 0x00000041 # Optional, defaults to 0xFFFFFFFF (receive everything).  Can be integer or hex
    lights:
      - light_1
```

I use this so that brightness is not reset to full when turned on using the switch.

**Comment by TMaYaD** [comment] 2023-12-23 01:24
FWIW, I can reproduce it intentionally and would be happy to assist with any debugging.

**Comment by Cossid** [comment] 2023-12-23 01:28
There isn't much good in you debugging if it's not fully reproducible for me, I won't be able to test what may need to be fixed.

Providing more information would be a better start.
What platform is the switch running on, what platform is the bulb running on?
What are the configs for each device?

**Comment by TMaYaD** [comment] 2023-12-23 01:45
Lights are H801. Switches are Tuya touch switches.

Full Light Config:
```yaml
substitutions:
  area: theater
  device: lights
  ip: 10.10.10.214
esphome:
  name: theater-lights
  area: theater
  build_path: build/theater-lights
  friendly_name: ''
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2023.12.3
esp8266:
  board: esp01_1m
  restore_from_flash: true
  framework:
    version: 3.0.2
    source: ~3.30002.0
    platform_version: platformio/espressif8266@3.2.0
  early_pin_init: true
  board_flash_mode: dout
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
api:
  encryption:
    key: \033[5m!secret 'encryption_key'\033[6m
  port: 6053
  password: \033[5m''\033[6m
  reboot_timeout: 15min
ota:
  password: \033[5m!secret 'ota_password'\033[6m
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
wifi:
  manual_ip:
    static_ip: 10.10.10.214
    gateway: 10.10.10.1
    subnet: 255.255.254.0
    dns1: 10.10.8.35
    dns2: 10.10.8.53
  ap:
    ssid: \033[5mtheater-lights\033[6m
    password: \033[5m!secret 'ap_password'\033[6m
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  passive_scan: false
  enable_on_boot: true
  networks:
  - ssid: \033[5m!secret 'wifi_ssid'\033[6m
    password: \033[5m!secret 'wifi_password'\033[6m
    priority: 0.0
  use_address: 10.10.10.214
captive_portal: {}
mqtt:
  broker: 10.10.8.33
  discovery: false
  topic_prefix: theater
  log_topic:
    topic: theater/lights/log
    level: INFO
    qos: 0
    retain: true
  port: 1883
  username: ''
  password: \033[5m''\033[6m
  discovery_retain: true
  discovery_prefix: homeassistant
  discovery_unique_id_generator: legacy
  discovery_object_id_generator: none
  use_abbreviations: true
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: theater/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
external_components:
- source:
    url: https://github.com/dentra/esphome-components.git
    type: git
  refresh: 1d
  components: all
- source:
    url: https://github.com/cossid/tasmotadevicegroupsforesphome.git
    ref: main
    type: git
  components:
  - device_groups
  refresh: 1d
backup:
  force_update: false
button:
- platform: restart
  name: theater lights Restart
  disabled_by_default: true
  entity_category: config
  device_class: restart
output:
- platform: esp8266_pwm
  id: pwm_r
  pin:
    number: 15
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_g
  pin:
    number: 13
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_b
  pin:
    number: 12
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_w1
  pin:
    number: 14
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
- platform: esp8266_pwm
  id: pwm_w2
  pin:
    number: 4
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  frequency: 1000.0
  zero_means_zero: false
light:
- platform: monochromatic
  id: light_1
  output: pwm_r
  restore_mode: RESTORE_DEFAULT_OFF
  name: theater Room Lights
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
- platform: monochromatic
  id: light_2
  output: pwm_g
  restore_mode: RESTORE_DEFAULT_OFF
  name: theater Entry Lights
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
- platform: monochromatic
  id: light_3
  output: pwm_b
  restore_mode: RESTORE_DEFAULT_OFF
  name: theater Bath Lights
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
- platform: monochromatic
  id: light_4
  output: pwm_w1
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  name: light_4
  internal: true
- platform: monochromatic
  id: light_5
  output: pwm_w2
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  gamma_correct: 2.8
  default_transition_length: 1s
  flash_transition_length: 0s
  name: light_5
  internal: true
device_groups:
- group_name: theater-lights
  lights:
  - light_1
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
- group_name: theater-entry-lights
  receive_mask: 0x01
  lights:
  - light_2
  send_mask: 0xFFFFFFFF
- group_name: theater-bath-lights
  receive_mask: 0x01
  lights:
  - light_3
  send_mask: 0xFFFFFFFF
```

Full Switch config:
```yaml
substitutions:
  area: theater
  device: entry
  ip: 10.10.10.211
esphome:
  name: theater-entry
  area: theater
  build_path: build/theater-entry
  friendly_name: ''
  platformio_options: {}
  includes: []
  libraries: []
  name_add_mac_suffix: false
  min_version: 2023.12.3
esp8266:
  board: esp01_1m
  restore_from_flash: true
  framework:
    version: 3.0.2
    source: ~3.30002.0
    platform_version: platformio/espressif8266@3.2.0
  early_pin_init: true
  board_flash_mode: dout
logger:
  baud_rate: 0
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
  esp8266_store_log_strings_in_flash: true
api:
  encryption:
    key: \033[5m!secret 'encryption_key'\033[6m
  port: 6053
  password: \033[5m''\033[6m
  reboot_timeout: 15min
ota:
  password: \033[5m!secret 'ota_password'\033[6m
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10
wifi:
  manual_ip:
    static_ip: 10.10.10.211
    gateway: 10.10.10.1
    subnet: 255.255.254.0
    dns1: 10.10.8.35
    dns2: 10.10.8.53
  ap:
    ssid: \033[5mtheater-entry\033[6m
    password: \033[5m!secret 'ap_password'\033[6m
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  passive_scan: false
  enable_on_boot: true
  networks:
  - ssid: \033[5m!secret 'wifi_ssid'\033[6m
    password: \033[5m!secret 'wifi_password'\033[6m
    priority: 0.0
  use_address: 10.10.10.211
captive_portal: {}
mqtt:
  broker: 10.10.8.33
  discovery: false
  topic_prefix: theater
  log_topic:
    topic: theater/entry/log
    level: INFO
    qos: 0
    retain: true
  port: 1883
  username: ''
  password: \033[5m''\033[6m
  discovery_retain: true
  discovery_prefix: homeassistant
  discovery_unique_id_generator: legacy
  discovery_object_id_generator: none
  use_abbreviations: true
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: theater/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: theater/status
    payload: offline
    qos: 0
    retain: true
external_components:
- source:
    url: https://github.com/dentra/esphome-components.git
    type: git
  refresh: 1d
  components: all
- source:
    url: https://github.com/cossid/tasmotadevicegroupsforesphome.git
    ref: main
    type: git
  components:
  - device_groups
  refresh: 1d
backup:
  force_update: false
button:
- platform: restart
  name: theater entry Restart
  disabled_by_default: true
  entity_category: config
  device_class: restart
tuya: {}
uart:
- rx_pin:
    number: 3
    mode:
      input: true
      output: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  tx_pin:
    number: 1
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
      analog: false
    inverted: false
  baud_rate: 9600
  rx_buffer_size: 256
  stop_bits: 1
  data_bits: 8
  parity: NONE
switch:
- platform: tuya
  id: switch_1
  switch_datapoint: 1
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_1
  internal: true
- platform: tuya
  id: switch_2
  switch_datapoint: 2
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_2
  internal: true
- platform: tuya
  id: switch_3
  switch_datapoint: 3
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_3
  internal: true
- platform: tuya
  id: switch_4
  switch_datapoint: 4
  restore_mode: RESTORE_DEFAULT_OFF
  disabled_by_default: false
  name: switch_4
  internal: true
device_groups:
- group_name: theater-lights
  switches:
  - switch_1
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
- group_name: theater-entry-lights
  switches:
  - switch_2
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
- group_name: theater-bath-lights
  switches:
  - switch_3
  send_mask: 0xFFFFFFFF
  receive_mask: 0xFFFFFFFF
```

**Comment by Cossid** [comment] 2023-12-23 02:18
There is a better than 0 chance this is because your switch is TuyaMCU based.  I don't have one to test with, so I'm not sure how to approach that.  Do you have any GPIO-based switches to test if you have the same issues?

Logs from the switch side would probably be more useful here than from the light.

**Comment by TMaYaD** [comment] 2023-12-23 02:24
I do have sonoff basic I can probably work with. 

However, I'm not convinced it's the switch side that's the problem. In the light logs I shared earlier, you can clearly see the light side receiving the message with payload `335544320`(I'm assuming the last bit is the power) as well as sending an ack. However, it fails to act on the message and turn the light off. 

I'll rerun the test and upload the switch side logs in a bit.

**Comment by bkbartk** [comment] 2023-12-26 14:53
Sorry, To break in to this thread,

but I have experienced this issue on a few of my configs, but only with a really specific scenario
tuya(libretiny) RGBWW light bulb.
sonoff NSPanel running this blueprint(https://github.com/Blackymas/NSPanel_HA_Blueprint)
when I click the buttons. all look fine,but when I go to HA and adjust the lights, sometimes the nspanel won't follow.
but also in the situation where I have 2 NSpanels and 2 bulbs, the NSpanels won't always follow each other, the scenario happens less often but this happens.
(in none of my other setups i use tuya bulbs or NSPanels and they all work like a charm)

First I thought it was because of tuya, but now I think the NSpanels are just sometimes to busy to receive and process the UDP request.

as a workaround I created a blueprint. to keep my lights and switches in sync. device grouping over UDP works way faster and better, but just in case it might fail, there is a fallback.
My blueprint is like this
```
blueprint:
  name: Combine switches so they turn on/off together
  description: Combine switches so they turn on/off together
  domain: automation
  input:
    switch_1:
      name: switch_1
      description: switch_1
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true
trigger:
  - platform: state
    entity_id: !input switch_1
    to:
      - "on"
      - "off"
action:
  - variables:
      modified_state: "{{ trigger.to_state.state }}"
      switches: !input switch_1
  - repeat:
      for_each: "{{ switches }}"
      sequence:
        - if: "{{ repeat.item.state != modified_state }}"
          then:
            - if: '{{ modified_state == "on" }}'
              then:
                - service: switch.turn_on
                  target:
                    entity_id: "{{ repeat.item }}"
              else:
                - service: switch.turn_off
                  target:
                    entity_id: "{{ repeat.item }}"
```
I know it's just workaround, but for me using both, (this component and the bleuprint works best)

**Comment by bkbartk** [comment] 2024-01-13 18:20
I did something else last week,
I migrated an esp32 device from tasmosta to ESPhome.
I while using tasmota I never noticed the sync not working,
now when the esphome device is on de receiving end I noticed sometimes the switch not turning off.
I'm not 100% sure the issue is only when turning off, andnot while turning on, but I haven't noticed the issue if it exists.
It can off course be that esphome works different internally an therefor is less alert, but it's something I noticed. and only when receiving the signal.

**Comment by ivanpavlina** [comment] 2024-02-03 13:50
I'm encountering the same issue. I have three Shelly Duo bulbs that I want to keep in sync. However, for some reason, the power command is sometimes not executed on the device which performed the power modification for the group in the last run.

So, I went through the code and logged some information. (I don't know C++, so this is all I've managed for now :P) However, I managed to trace the problem to line 574:

```
                if (on != (TasmotaGlobal.power & mask))
                  ExecuteCommandPower(i + 1, (on ? POWER_ON : POWER_OFF), SRC_REMOTE);
              }
```

`TasmotaGlobal.power & mask` returns the incorrect value for the current state of the light, even though the light was turned off through the web GUI (action propagated to other lights in the group). But when a message is received from another light requesting this light to turn on, this check perceives the light as still being on, and no action is taken.

I'm not sure why this is happening, but I "fixed" it by commenting out this `if` statement and always calling `ExecuteCommandPower`, regardless of the current state.

I'm satisfied with it for now as it is, but I hope this gives you some insight for a real fix.

**Comment by Cossid** [comment] 2024-02-03 21:33
I found a place power toggling may not have properly been sending a status update.  Please update and see if things have changed or if they are still the same.

**Comment by ivanpavlina** [comment] 2024-02-04 08:03
Hi, thank you for the fast response!
Unfortunately, it didn't help; the same issue is still occurring with the new code.

It seems `ExecuteCommandPower` is not executed when doing local power toggling, only when a power toggle is received from another device. I don't know if that's expected, but as far as I can see, there is no update to the `TasmotaGlobal.power` variable in the case of a local power toggle. So, in the next message that is received, the power status is in an incorrect state.

**Comment by bkbartk** [comment] 2024-02-04 10:50
this is purely curiosity and probably won't brake anything
but I don't think POWER_TOGGLE can be a state?
```
 if (state <= POWER_TOGGLE) {
    switch (state) {
      case POWER_OFF: {
        TasmotaGlobal.power &= (POWER_MASK ^ mask);
        break;
      }
      case POWER_ON:
        TasmotaGlobal.power |= mask;
        break;
      case POWER_TOGGLE:
        TasmotaGlobal.power ^= mask;
    }
  }
```
also for both references, it's either Power_off or Power_On
`ExecuteCommandPower(device, (on ? POWER_ON : POWER_OFF), SRC_REMOTE);`

I haven't had the time to test the created change. I will do this later,

**Comment by Cossid** [comment] 2024-02-04 15:09
> Hi, thank you for the fast response! Unfortunately, it didn't help; the same issue is still occurring with the new code.
> 
> It seems `ExecuteCommandPower` is not executed when doing local power toggling, only when a power toggle is received from another device. I don't know if that's expected, but as far as I can see, there is no update to the `TasmotaGlobal.power` variable in the case of a local power toggle. So, in the next message that is received, the power status is in an incorrect state.

Thanks for that insight, that is starting to make more sense (though I still can't explain why my devices seem fine the way it is).  I have applied another update, please give it a try.  It is now using ExecuteCommandPower for local commands so that masking is applied in all cases, not just remote.

**Comment by Cossid** [comment] 2024-02-04 15:11
> this is purely curiosity and probably won't brake anything but I don't think POWER_TOGGLE can be a state?
> 

> also for both references, it's either Power_off or Power_On `ExecuteCommandPower(device, (on ? POWER_ON : POWER_OFF), SRC_REMOTE);`
> 
> I haven't had the time to test the created change. I will do this later,

That is Tasmota code, but the code is <= POWER_TOGGLE, and POWER_ON and POWER_OFF are both less than POWER_TOGGLE.  Indeed I am not using POWER_TOGGLE in the ESPHome code, but it is fine as-is, the issue was lack of applying a power mask on local commands I think.  Please try the latest code when you get a chance and let me know if it improves.

**Comment by ivanpavlina** [comment] 2024-02-04 15:30
> > this is purely curiosity and probably won't brake anything but I don't think POWER_TOGGLE can be a state?
> 
> > also for both references, it's either Power_off or Power_On `ExecuteCommandPower(device, (on ? POWER_ON : POWER_OFF), SRC_REMOTE);`
> > I haven't had the time to test the created change. I will do this later,
> 
> That is Tasmota code, but the code is <= POWER_TOGGLE, and POWER_ON and POWER_OFF are both less than POWER_TOGGLE. Indeed I am not using POWER_TOGGLE in the ESPHome code, but it is fine as-is, the issue was lack of applying a power mask on local commands I think. Please try the latest code when you get a chance and let me know if it improves.

Awesome! Looks good from my end, every request is handled correctly now. Now I added 4 bulbs in one group, toggling them on/off from different places at random (web gui, homeassistant), toggles every light correctly every time.

Thank you my guy, great job!

**Comment by bkbartk** [comment] 2024-02-05 18:26
for some reason for me it still fails.
```
19:08:44	[D]	[switch:016]	'Lamp Garage Achter' Turning OFF.
19:08:45	[D]	[switch:055]	'Lamp Garage Achter': Sending state OFF
19:08:45	[D]	[dgr:735]	Sending Garage message to network: seq=16, flags=0, 128=335544320
19:08:46	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=16, flags=8
19:09:03	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=2, flags=64
19:09:29	[D]	[switch:012]	'Lamp Garage Achter' Turning ON.
19:09:30	[D]	[switch:055]	'Lamp Garage Achter': Sending state ON
19:09:32	[D]	[dgr:735]	Sending Garage message to network: seq=17, flags=0, 128=335544321
19:09:32	[D]	[dgr:735]	Sending Garage message to network: seq=17, flags=0, 128=335544321
19:09:32	[D]	[dgr:735]	Sending Garage message to 192.168.180.146: seq=17, flags=0, last ack=16
19:09:32	[D]	[dgr:735]	Sending Garage message to 192.168.180.146: seq=17, flags=0, last ack=16
19:09:33	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=17, flags=8
19:09:35	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=17, flags=8
19:10:09	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=2, flags=64
19:10:27	[D]	[switch:016]	'Lamp Garage Achter' Turning OFF.
19:10:29	[D]	[switch:055]	'Lamp Garage Achter': Sending state OFF
19:10:29	[D]	[dgr:735]	Sending Garage message to network: seq=18, flags=0, 128=335544320
19:10:29	[D]	[dgr:735]	Sending Garage message to network: seq=18, flags=0, 128=335544320
19:10:29	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=18, flags=8
19:10:33	[D]	[switch:012]	'Lamp Garage Achter' Turning ON.
19:10:33	[D]	[switch:055]	'Lamp Garage Achter': Sending state ON
19:10:33	[D]	[dgr:735]	Sending Garage message to network: seq=19, flags=0, 128=335544321
19:10:33	[D]	[dgr:735]	Sending Garage message to network: seq=19, flags=0, 128=335544321
19:10:33	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=19, flags=8
19:11:15	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=2, flags=64
19:12:24	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=2, flags=64
19:12:31	[D]	[switch:016]	'Lamp Garage Achter' Turning OFF.
19:12:31	[D]	[switch:055]	'Lamp Garage Achter': Sending state OFF
19:12:34	[D]	[dgr:735]	Sending Garage message to network: seq=20, flags=0, 128=335544320
19:12:34	[D]	[dgr:735]	Sending Garage message to network: seq=20, flags=0, 128=335544320
19:12:34	[D]	[dgr:735]	Sending Garage message to 192.168.180.146: seq=20, flags=0, last ack=19
19:12:34	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=20, flags=8
19:12:35	[D]	[switch:012]	'Lamp Garage Achter' Turning ON.
19:12:35	[D]	[switch:055]	'Lamp Garage Achter': Sending state ON
19:12:35	[D]	[dgr:735]	Sending Garage message to network: seq=21, flags=0, 128=335544321
19:12:35	[D]	[dgr:735]	Sending Garage message to network: seq=21, flags=0, 128=335544321
19:12:35	[D]	[dgr:735]	Sending Garage message to 192.168.180.146: seq=21, flags=0, last ack=20
19:12:35	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=21, flags=8
19:12:40	[D]	[switch:016]	'Lamp Garage Achter' Turning OFF.
19:12:42	[D]	[switch:055]	'Lamp Garage Achter': Sending state OFF
19:12:42	[D]	[dgr:735]	Sending Garage message to network: seq=22, flags=0, 128=335544320
19:12:42	[D]	[dgr:735]	Sending Garage message to network: seq=22, flags=0, 128=335544320
19:12:43	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=22, flags=8
19:12:43	[D]	[dgr:735]	Received Garage message from 192.168.180.146: seq=22, flags=8
19:12:44	[D]	[switch:016]	'Lamp Garage Achter' Turning OFF.
19:14:42	[D]	[dgr:735]   Received Garage message from 192.168.180.146: seq=2, flags=64
```
So I Looked at the logs at the sending side and noticed two wierd things,
at some point the signal gets send 4 times in a row, 2 for network, and 2 to the specific other node.
but the last thing is more interesting.
on 19:12:40 and 19:12:44 the switch both says  Turning OFF where the latter turned ON the switch as it was already off. resulting in the other part not following the turn on signal.

then to be fully completed also the log from the receiving switch
```
19:08:45	[D]	[switch:055]	'Lamp Garage voor': Sending state OFF
19:08:45	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=16, flags=0, 128=335544320*
19:08:45	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=16, flags=0, 128=335544320*
19:09:03	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:09:29	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=17, flags=8
19:09:29	[D]	[switch:012]	'Lamp Garage voor' Turning ON.
19:09:29	[D]	[switch:055]	'Lamp Garage voor': Sending state ON
19:09:29	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=17, flags=0, 128=335544321*
19:09:30	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=17, flags=8
19:09:30	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=17, flags=0 (old)
19:09:30	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=17, flags=0 (old)
19:10:09	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:10:28	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=18, flags=8
19:10:28	[D]	[switch:016]	'Lamp Garage voor' Turning OFF.
19:10:28	[D]	[switch:055]	'Lamp Garage voor': Sending state OFF
19:10:28	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=18, flags=0, 128=335544320*
19:10:33	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=19, flags=8
19:10:33	[D]	[switch:012]	'Lamp Garage voor' Turning ON.
19:10:33	[D]	[switch:055]	'Lamp Garage voor': Sending state ON
19:10:33	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=19, flags=0, 128=335544321*
19:11:15	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:12:24	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:12:31	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=20, flags=8
19:12:31	[D]	[switch:016]	'Lamp Garage voor' Turning OFF.
19:12:31	[D]	[switch:055]	'Lamp Garage voor': Sending state OFF
19:12:31	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=20, flags=0, 128=335544320*
19:12:35	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=21, flags=8
19:12:35	[D]	[switch:012]	'Lamp Garage voor' Turning ON.
19:12:35	[D]	[switch:055]	'Lamp Garage voor': Sending state ON
19:12:35	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=21, flags=0, 128=335544321*
19:12:35	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=21, flags=0, 128=335544321*
19:12:40	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=22, flags=8
19:12:40	[D]	[switch:016]	'Lamp Garage voor' Turning OFF.
19:12:40	[D]	[switch:055]	'Lamp Garage voor': Sending state OFF
19:12:40	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=0, 128=335544320*
19:12:40	[D]	[dgr:735]	Sending Garage message to 192.168.180.179: seq=22, flags=8
19:12:40	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=0 (old)
19:12:40	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=0 (old)
19:13:33	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:14:40	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=64
19:14:42	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:15:44	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=64
19:15:52	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:17:01	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:17:03	[D]	[time:045]	Synchronized time: 2024-02-05 
19:17:04
19:17:56	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=64
19:18:11	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:19:05	[D]	[dgr:735]	Received Garage message from 192.168.180.179: seq=22, flags=64
19:19:13	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
19:20:19	[D]	[dgr:735]	Sending Garage message to network: seq=2, flags=64
```

I used the esphome webinterface or my first device to toggle the switch.

**Comment by Cossid** [comment] 2024-02-05 18:45
Those logs look correct to me, where it is sending on with on and off with off

> at some point the signal gets send 4 times in a row, 2 for network, and 2 to the specific other node.
but the last thing is more interesting.

This isn't that unusual.  UDP is unreliable, and the code is set up to automatically retry and de-dupe.

> on 19:12:40 and 19:12:44 the switch both says Turning OFF where the latter turned ON the switch as it was already off. resulting in the other part not following the turn on signal.

Something else must be at play here, the command from ESPHome was clearly 'OFF', and we aren't using toggle anywhere.  If your device is doing something other than what it is saying, something else must be at play.

**Comment by bkbartk** [comment] 2024-02-05 19:01
> something else must be at play.
I did some more tests, also using the HA dashboard, and the once using using HA all went well.
i looks like the esphome webinterface at some point just sends the wrong command to the device and in the the meanwhile also shows an incorrect state.

so sorry for that, I think it works, I will check in the coming days for issues.

Then I only have issues on my nspanels, but I believe that's because the esp is too busy handling all requests from the blueprint, so that's something not related to this project.

**Comment by Cossid** [comment] 2024-02-28 14:58
I am closing this issue, as it appears to be resolved as best I understand it.  If there are still issues, please create a new issue with specific reproduction steps, device info, and logs.

**Closed by Cossid** 2024-02-28 14:58 UTC
